server:
  port: 9637

spring:
  profiles:
    active: prod
  application:
    name: petrel-game-chess
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 202.189.7.196:6878

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: Fagp_1908

nacos:
  username: nacos
  password: nacos
  server-addr: 127.0.0.1:6878


zebra:
  port: 9637
  ip:
    out: 202.189.7.196
    in: 10.0.0.1
  size: 0
  weight: 50

game:
  contains: 1  #0 不包含， 1 包含
  list: 0

logging:
  config: classpath:logback-spring.xml
  level:
    com.petrel.chess: INFO



